name: ZIYAD AI NEWS

on:
  schedule:
    - cron: '0 22 * * 0'
    - cron: '0 22 * * 2'
  workflow_dispatch:

jobs:
  send-news:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    concurrency:
      group: ziyad-ai-news
      cancel-in-progress: true

    steps:
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl grep coreutils sed gawk

      - name: Fetch RSS
        run: |
          curl -s https://hnrss.org/frontpage > rss.xml

      - name: Extract titles and links
        run: |
          grep -oP '(?<=<title>).*?(?=</title>)' rss.xml \
          | tail -n +2 \
          | sed 's/<!\[CDATA\[//g; s/\]\]>//g' > titles.txt

          grep -oP '(?<=<link>).*?(?=</link>)' rss.xml \
          | tail -n +2 > links.txt

      - name: Filter AI & Developer News
        run: |
          paste -d '|' titles.txt links.txt | \
          grep -iE "ai|artificial intelligence|machine learning|gpt|llm|agent|developer|coding|programming|github|python|javascript|android|software|startup|openai|deepseek|nvidia" > filtered.txt

      - name: Rank Best News
        run: |
          awk -F '|' '
          {
            score=0

            title=tolower($1)

            if (title ~ /ai|gpt|llm|agent|openai|deepseek|nvidia/) score+=4
            if (title ~ /launch|release|new|future|breaking/) score+=3
            if (title ~ /developer|coding|programming|github/) score+=2
            if (length($1) > 60) score+=1

            print score "|" $0
          }' filtered.txt | sort -t'|' -nr | head -n 1 > best.txt

      - name: Create News Message
        run: |
          TITLE=$(cut -d '|' -f2 best.txt)
          LINK=$(cut -d '|' -f3 best.txt)

          NEWS_ID="NEWS-$(date +%Y%m%d%H%M)"

          echo "🚀 ZIYAD AI INSIGHT" > news.txt
          echo "" >> news.txt

          echo "🆔 $NEWS_ID" >> news.txt
          echo "" >> news.txt

          echo "🔥 $TITLE" >> news.txt
          echo "" >> news.txt

          echo "🧠 Ringkasan:" >> news.txt
          echo "Berita ini sedang ramai di dunia teknologi karena berpotensi memengaruhi perkembangan AI, software, developer, dan industri digital modern." >> news.txt
          echo "" >> news.txt

          echo "💬 Reply pesan ini untuk bertanya ke AI tentang berita ini." >> news.txt
          echo "" >> news.txt

          echo "📰 Source: Hacker News" >> news.txt
          echo "" >> news.txt

          echo "🔗 $LINK" >> news.txt

      - name: Debug Output
        run: cat news.txt

      - name: Send to Telegram
        run: |
          TEXT=$(cat news.txt)

          if [ -n "$TEXT" ]; then
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.CHAT_ID }} \
            --data-urlencode text="$TEXT"
          else
            echo "No news found"
          fi
